/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your appointments
         * @description One path, dispatched on method - the conventional shape, and the one
         *     docs/03 specifies.
         */
        get: operations["appointments_list"];
        put?: never;
        /**
         * Book an appointment
         * @description One path, dispatched on method - the conventional shape, and the one
         *     docs/03 specifies.
         */
        post: operations["appointments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One appointment
         * @description Scoped to the caller: an enumerated id must not reveal somebody else's
         *     appointment.
         */
        get: operations["appointment_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an appointment */
        post: operations["appointments_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a sign-in code
         * @description Always returns 204, whether or not the number is known - the response must not reveal which numbers are registered.
         */
        post: operations["auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a sign-in code for tokens */
        post: operations["auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Districts with verified facilities
         * @description Drives the fallback picker when geolocation is denied or out of bounds,
         *     and the first USSD menu in Phase 3.
         */
        get: operations["districts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facility detail */
        get: operations["facilities_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/{slug}/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctors practising at a facility */
        get: operations["facility_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bookable slots for a facility and service */
        get: operations["facilities_slots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearby facilities
         * @description Verified facilities near a coordinate, ranked by (tier, distance). Results are never ranked by wait time - only a minority of facilities report queue data, so ranking on it would bury good facilities that simply do not report.
         */
        get: operations["facilities_nearby_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insurers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insurers
         * @description Reference list. Changes perhaps twice a year - cache for 24h client-side.
         */
        get: operations["insurers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in patient */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        /**
         * Erase your account
         * @description The right of erasure. Records are anonymised rather than deleted: the facility keeps its attendance counts, which every other patient's wait estimate depends on, and you are no longer identifiable in them. This cannot be undone.
         */
        delete: operations["me_destroy"];
        options?: never;
        head?: never;
        /** Update the signed-in patient */
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export everything held about you
         * @description The right of access under Rwanda Law 058/2021. Returns the profile, appointment and queue history, and every message sent - in one document. Symptom-checker answers are not included because they are never stored against an account.
         */
        get: operations["me_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which messages you receive */
        get: operations["notification_preferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Turn one kind of message on or off */
        patch: operations["notification_preferences_update"];
        trace?: never;
    };
    "/api/v1/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages MediLink has sent you */
        get: operations["notification_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctors directory */
        get: operations["provider_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor profile */
        get: operations["provider_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue board for the caller's facility
         * @description Everything the reception screen needs, grouped by service.
         */
        get: operations["queue_board_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in patient's active queue entry
         * @description What the patient home screen calls on load to choose between
         *     state A (nothing active) and state B (in a queue).
         *
         *     204 when there is nothing active - an empty body, not an error.
         */
        get: operations["queue_current_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check a patient in
         * @description The most performance-sensitive write in the system. Send an Idempotency-Key header: a retry after a network timeout must return the original entry, not create a duplicate.
         */
        post: operations["queue_entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One queue entry (patient-facing view)
         * @description Polled by the patient every 20 seconds.
         *
         *     Scoped to the caller: a patient sees only their own entry, and facility
         *     staff see only entries at their own facility. Without this, an enumerated
         *     id reveals a stranger's position in a health queue.
         */
        get: operations["queue_entries_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/entries/{id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a queue entry: call, serve, skip or cancel */
        post: operations["queue_entry_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay actions recorded while the reception client was offline
         * @description Apply queued offline actions, oldest client timestamp first.
         *
         *     Per-item results, so one rejected action does not fail the whole batch -
         *     a receptionist reconnecting after an hour must not lose the other 39
         *     check-ins because one patient was a duplicate.
         */
        post: operations["queue_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One search across specialties, services, doctors and facilities
         * @description A patient typing 'pediatric' does not know whether that is a service, a specialty, a doctor or a hospital. Results come back grouped, ordered by what gets somebody to care fastest. Empty groups are omitted rather than returned empty.
         */
        get: operations["global_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service types
         * @description Small, cacheable reference list. Includes all three language names so
         *     that USSD and WhatsApp can render without a second call.
         */
        get: operations["service_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Specialties
         * @description The shared clinical vocabulary. Each specialty carries the facility service codes a clinician in it delivers, which is what lets a Care Guide recommendation reach the facility search.
         */
        get: operations["specialties_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in staff member and their facility
         * @description The reception client calls this on load to learn which facility it is
         *     operating, and which services that facility offers.
         */
        get: operations["staff_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a triage session */
        post: operations["triage_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage/sessions/{session_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer the current question */
        post: operations["triage_sessions_answer_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether the symptom checker is available
         * @description Reports whether a clinician sign-off has been recorded. The client must hide the symptom checker entirely when this returns available=false, rather than showing a broken entry point.
         */
        get: operations["triage_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Answer: {
            question: string;
            option: string;
        };
        Appointment: {
            readonly id: number;
            readonly reference: string;
            readonly status: components["schemas"]["AppointmentStatusEnum"];
            readonly facility: components["schemas"]["AppointmentFacility"];
            readonly service: string;
            readonly provider: string | null;
            /** Format: date-time */
            readonly slot_start: string;
            /** Format: date-time */
            readonly slot_end: string;
        };
        AppointmentFacility: {
            name: string;
            slug: string;
            phone: string;
        };
        /**
         * @description * `booked` - Booked
         *     * `arrived` - Arrived
         *     * `served` - Served
         *     * `no_show` - No show
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        AppointmentStatusEnum: "booked" | "arrived" | "served" | "no_show" | "cancelled";
        Board: {
            facility: components["schemas"]["BoardFacility"];
            as_of: string;
            services: components["schemas"]["ServiceGroup"][];
        };
        BoardFacility: {
            name: string;
            slug: string;
        };
        Booking: {
            facility: string;
            service: string;
            provider?: string | null;
            /** Format: date-time */
            slot_start: string;
        };
        /**
         * @description Minimal on purpose.
         *
         *     Target is under 10 seconds of human time per check-in, so the payload is a
         *     service plus one identifier. `facility` is never accepted from the client -
         *     it is derived from the authenticated staff member, so a receptionist cannot
         *     check a patient into another facility.
         */
        CheckIn: {
            service: string;
            phone?: string;
            walk_in_name?: string;
            /** Format: date-time */
            client_recorded_at?: string;
        };
        /** @description The check-in response is an entry plus its live ETA fields. */
        CheckInResponse: {
            readonly id: number;
            readonly ticket_code: string;
            /**
             * @description Masked too.
             *
             *     The model's display_name property falls back to the raw phone when a
             *     patient has no name on file. Masking `phone` while echoing the same
             *     number in `display_name` would defeat the point, so the fallback is
             *     masked here as well.
             */
            readonly display_name: string;
            /**
             * @description Masked. A queue board is readable across a reception desk, and a
             *     full phone number on screen is a needless disclosure.
             */
            readonly phone: string;
            readonly service: string;
            readonly status: components["schemas"]["QueueEntryStatusEnum"];
            readonly position: number;
            /** Format: date-time */
            readonly joined_at: string;
            /** Format: date-time */
            readonly called_at: string | null;
            readonly waited_minutes: number;
            eta_minutes: number | null;
            eta_confidence: string | null;
            people_ahead: number;
        };
        DistrictList: {
            results: string[];
        };
        FacilityDetail: {
            readonly id: number;
            slug: string;
            name: string;
            level: components["schemas"]["LevelEnum"];
            ownership: components["schemas"]["OwnershipEnum"];
            province?: string;
            district: string;
            sector?: string;
            address?: string;
            readonly location: components["schemas"]["LocationField"];
            phone?: string;
            /** Format: email */
            email?: string;
            readonly is_open: boolean;
            readonly opening_hours: components["schemas"]["OpeningHours"][];
            readonly insurers: components["schemas"]["InsurerBrief"][];
            readonly services: components["schemas"]["ServiceBrief"][];
            readonly wait: components["schemas"]["Wait"];
            readonly directions_url: string;
            /** Format: date-time */
            verified_at?: string | null;
        };
        FacilityNearby: {
            readonly id: number;
            slug: string;
            name: string;
            level: components["schemas"]["LevelEnum"];
            ownership: components["schemas"]["OwnershipEnum"];
            district: string;
            sector?: string;
            readonly location: components["schemas"]["LocationField"];
            readonly distance_m: number;
            phone?: string;
            readonly is_open: boolean;
            readonly opens_at: string | null;
            readonly closes_at: string | null;
            /** @description A patient must not travel to a door that shuts on arrival. */
            readonly closing_soon: boolean;
            readonly accepts_insurer: boolean;
            readonly insurers: string[];
            readonly services: string[];
            readonly wait: components["schemas"]["Wait"];
            readonly bookable: boolean;
        };
        Insurer: {
            code: string;
            name: string;
            is_public: boolean;
        };
        InsurerBrief: {
            code: string;
            name: string;
            note: string;
        };
        InsurerList: {
            results: components["schemas"]["Insurer"][];
        };
        /**
         * @description * `specialty` - specialty
         *     * `service` - service
         *     * `provider` - provider
         *     * `facility` - facility
         * @enum {string}
         */
        KindEnum: "specialty" | "service" | "provider" | "facility";
        /**
         * @description * `rw` - Kinyarwanda
         *     * `en` - English
         *     * `fr` - Francais
         * @enum {string}
         */
        LanguageEnum: "rw" | "en" | "fr";
        /**
         * @description * `health_post` - Health post
         *     * `health_centre` - Health centre
         *     * `district_hospital` - District hospital
         *     * `referral_hospital` - Referral hospital
         *     * `clinic` - Clinic / polyclinic
         *     * `pharmacy` - Pharmacy
         * @enum {string}
         */
        LevelEnum: "health_post" | "health_centre" | "district_hospital" | "referral_hospital" | "clinic" | "pharmacy";
        LocationField: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        NearbyQueryEcho: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            radius: number;
            radius_expanded: boolean;
            insurer: string | null;
            service: string | null;
            specialty: string | null;
            open_now: boolean;
        };
        NearbyResponse: {
            as_of: string;
            query: components["schemas"]["NearbyQueryEcho"];
            count: number;
            results: components["schemas"]["FacilityNearby"][];
        };
        /**
         * @description What was sent to this patient. Read-only: a notification is a record of
         *     something that happened, never something a client authors.
         */
        Notification: {
            readonly id: number;
            readonly kind: string;
            readonly kind_label: string;
            readonly channel: string;
            readonly body: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly sent_at: string | null;
        };
        NotificationList: {
            count: number;
            results: components["schemas"]["Notification"][];
        };
        OTPRequest: {
            phone: string;
        };
        OTPVerify: {
            phone: string;
            code: string;
        };
        OpeningHours: {
            weekday: number;
            /** Format: time */
            opens_at: string;
            /** Format: time */
            closes_at: string;
        };
        /**
         * @description * `public` - Public
         *     * `private` - Private
         *     * `faith_based` - Faith-based
         * @enum {string}
         */
        OwnershipEnum: "public" | "private" | "faith_based";
        PatchedPatient: {
            readonly id?: number;
            readonly phone?: string;
            full_name?: string;
            language?: components["schemas"]["LanguageEnum"];
            insurer?: string | null;
            readonly home_location?: {
                [key: string]: unknown;
            } | null;
        };
        PatchedPreferenceUpdate: {
            kind?: string;
            enabled?: boolean;
        };
        Patient: {
            readonly id: number;
            readonly phone: string;
            full_name?: string;
            language?: components["schemas"]["LanguageEnum"];
            insurer?: string | null;
            readonly home_location: {
                [key: string]: unknown;
            } | null;
        };
        Placement: {
            facility_slug: string;
            facility_name: string;
            district: string;
            role_title: string;
            services: string[];
        };
        Preference: {
            kind: string;
            label: string;
            enabled: boolean;
            can_disable: boolean;
        };
        PreferenceList: {
            results: components["schemas"]["Preference"][];
        };
        Provider: {
            readonly slug: string;
            readonly display_name: string;
            readonly full_name: string;
            readonly initials: string;
            readonly photo_url: string;
            readonly languages: string[];
            readonly specialties: string[];
            readonly placements: components["schemas"]["Placement"][];
            readonly verified: boolean;
        };
        ProviderDetail: {
            readonly slug: string;
            readonly display_name: string;
            readonly full_name: string;
            readonly initials: string;
            readonly photo_url: string;
            readonly languages: string[];
            readonly specialties: string[];
            readonly placements: components["schemas"]["Placement"][];
            readonly verified: boolean;
            /** @description Short professional summary. Never enter qualifications or claims that have not been verified - see docs/11 section 7. */
            bio_en?: string;
        };
        ProviderList: {
            count: number;
            results: components["schemas"]["Provider"][];
        };
        /** @description Staff-facing view of one entry. */
        QueueEntry: {
            readonly id: number;
            readonly ticket_code: string;
            /**
             * @description Masked too.
             *
             *     The model's display_name property falls back to the raw phone when a
             *     patient has no name on file. Masking `phone` while echoing the same
             *     number in `display_name` would defeat the point, so the fallback is
             *     masked here as well.
             */
            readonly display_name: string;
            /**
             * @description Masked. A queue board is readable across a reception desk, and a
             *     full phone number on screen is a needless disclosure.
             */
            readonly phone: string;
            readonly service: string;
            readonly status: components["schemas"]["QueueEntryStatusEnum"];
            readonly position: number;
            /** Format: date-time */
            readonly joined_at: string;
            /** Format: date-time */
            readonly called_at: string | null;
            readonly waited_minutes: number;
        };
        /**
         * @description Patient-facing view - no other patient's details, ever.
         *
         *     Phase 2 adds leave_by and travel_minutes here.
         */
        QueueEntryPublic: {
            readonly id: number;
            readonly facility: components["schemas"]["QueueFacility"];
            readonly service: string;
            readonly ticket_code: string;
            readonly status: components["schemas"]["QueueEntryStatusEnum"];
            readonly position: number;
            readonly people_ahead: number;
            readonly eta_minutes: number | null;
            readonly eta_confidence: string | null;
            readonly travel_minutes: number | null;
            /**
             * @description The sentence the whole product exists for.
             *
             *     Null when we cannot compute it - the client then hides the line
             *     entirely rather than showing a time somebody might act on.
             */
            readonly leave_by: string | null;
            /** Format: date-time */
            readonly joined_at: string;
            readonly as_of: string;
        };
        /**
         * @description * `waiting` - Waiting
         *     * `called` - Called
         *     * `served` - Served
         *     * `left` - Left without being seen
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        QueueEntryStatusEnum: "waiting" | "called" | "served" | "left" | "cancelled";
        QueueFacility: {
            name: string;
            slug: string;
            location: components["schemas"]["QueueLocation"];
        };
        QueueLocation: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        SearchGroup: {
            kind: components["schemas"]["KindEnum"];
            results: components["schemas"]["SearchResult"][];
        };
        SearchResponse: {
            query: string;
            groups: components["schemas"]["SearchGroup"][];
        };
        SearchResult: {
            code: string;
            label: string;
            label_rw?: string;
            label_fr?: string;
            sublabel?: string;
            distance_m?: number | null;
            href: string;
            routable: boolean;
        };
        ServiceBrief: {
            code: string;
            name_rw: string;
            name_en: string;
            name_fr: string;
            wait: components["schemas"]["Wait"];
            coverage: components["schemas"]["ServiceCoverage"][];
        };
        ServiceCoverage: {
            insurer: string;
            insurer_name: string;
            coverage: string;
            note: string;
        };
        ServiceGroup: {
            service: string;
            service_name_rw: string;
            service_name_en: string;
            waiting: components["schemas"]["QueueEntry"][];
            called: components["schemas"]["QueueEntry"][];
        };
        ServiceType: {
            code: string;
            name_rw: string;
            name_en: string;
            name_fr: string;
        };
        ServiceTypeList: {
            results: components["schemas"]["ServiceType"][];
        };
        Slot: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            remaining: number;
            capacity: number;
        };
        SlotDay: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["Slot"][];
        };
        SlotDays: {
            facility: string;
            service: string;
            provider: string | null;
            as_of: string;
            days: components["schemas"]["SlotDay"][];
        };
        Specialty: {
            code: string;
            name_rw: string;
            name_en: string;
            name_fr: string;
            description_en?: string;
            readonly service_types: string[];
            is_triage_target?: boolean;
        };
        SpecialtyList: {
            results: components["schemas"]["Specialty"][];
        };
        StaffFacility: {
            id: number;
            slug: string;
            name: string;
            district: string;
            reports_queue: boolean;
        };
        StaffMe: {
            username: string;
            role: string;
            can_manage_queue: boolean;
            facility: components["schemas"]["StaffFacility"];
            services: components["schemas"]["StaffService"][];
        };
        StaffService: {
            code: string;
            name_rw: string;
            name_en: string;
        };
        Sync: {
            actions: components["schemas"]["SyncAction"][];
        };
        SyncAction: {
            key: string;
            type: components["schemas"]["TypeEnum"];
            /** Format: date-time */
            client_recorded_at: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        SyncResponse: {
            applied: number;
            rejected: number;
            results: components["schemas"]["SyncResultRow"][];
        };
        SyncResultRow: {
            key: string;
            ok: boolean;
            created?: boolean;
            entry_id?: number;
            ticket_code?: string;
            error?: string;
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenPair: {
            access: string;
            refresh: string;
            patient: components["schemas"]["Patient"];
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        Translation: {
            rw: string;
            en: string;
            fr: string;
        };
        TriageOption: {
            code: string;
            text: components["schemas"]["Translation"];
        };
        TriageQuestion: {
            code: string;
            red_flag: boolean;
            text: components["schemas"]["Translation"];
            options: components["schemas"]["TriageOption"][];
        };
        TriageSession: {
            session_id: string;
            protocol_version: string;
            approved_by: string;
            disclaimer: components["schemas"]["Translation"];
            escalate_emergency: boolean;
            emergency_advice: components["schemas"]["Translation"] | null;
            recommendation: string | null;
            finished: boolean;
            next_question: components["schemas"]["TriageQuestion"] | null;
        };
        TriageStatus: {
            available: boolean;
            protocol_version: string;
            approved_by: string;
            approved_on: string;
            reason: string;
        };
        /**
         * @description * `check_in` - check_in
         *     * `call` - call
         *     * `serve` - serve
         *     * `skip` - skip
         *     * `cancel` - cancel
         * @enum {string}
         */
        TypeEnum: "check_in" | "call" | "serve" | "skip" | "cancel";
        /**
         * @description The wait contract, enforced in the OpenAPI schema itself.
         *
         *     `status` is a ChoiceField rather than a CharField so the generated
         *     TypeScript client gets a closed union and a client that forgets to
         *     handle one of the four states fails to compile. There is deliberately
         *     no value meaning "estimated" - we never guess a wait time.
         *
         *     Defined above ServiceBriefSerializer because that one embeds it.
         */
        Wait: {
            status: components["schemas"]["WaitStatusEnum"];
            minutes: number | null;
            people_waiting: number | null;
            as_of: string;
        };
        /**
         * @description * `available` - available
         *     * `not_reported` - not_reported
         *     * `insufficient_data` - insufficient_data
         *     * `closed` - closed
         * @enum {string}
         */
        WaitStatusEnum: "available" | "not_reported" | "insufficient_data" | "closed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    appointments_list: {
        parameters: {
            query?: {
                /** @description upcoming | past | all */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"][];
                };
            };
        };
    };
    appointments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Booking"];
                "application/x-www-form-urlencoded": components["schemas"]["Booking"];
                "multipart/form-data": components["schemas"]["Booking"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    appointment_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    appointments_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
        };
    };
    auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OTPRequest"];
                "multipart/form-data": components["schemas"]["OTPRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["OTPVerify"];
                "multipart/form-data": components["schemas"]["OTPVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    districts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictList"];
                };
            };
        };
    };
    facilities_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDetail"];
                };
            };
        };
    };
    facility_providers: {
        parameters: {
            query?: {
                service?: string;
                specialty?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    facilities_slots_retrieve: {
        parameters: {
            query: {
                date_from?: string;
                date_to?: string;
                /** @description Provider slug. Omit for the facility general clinic - 'any available', which is the default and the common case. */
                provider?: string;
                service: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDays"];
                };
            };
        };
    };
    facilities_nearby_retrieve: {
        parameters: {
            query: {
                /** @description Insurer code, e.g. mutuelle */
                insurer?: string;
                lat: number;
                level?: string[];
                limit?: number;
                lng: number;
                open_now?: boolean;
                /** @description Metres. Default 5000, max 50000. */
                radius?: number;
                /** @description Service type code */
                service?: string;
                /** @description Specialty code, from a Care Guide recommendation */
                specialty?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyResponse"];
                };
            };
        };
    };
    insurers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsurerList"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
        };
    };
    me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPatient"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPatient"];
                "multipart/form-data": components["schemas"]["PatchedPatient"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
        };
    };
    me_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notification_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceList"];
                };
            };
        };
    };
    notification_preferences_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPreferenceUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPreferenceUpdate"];
                "multipart/form-data": components["schemas"]["PatchedPreferenceUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceList"];
                };
            };
        };
    };
    notification_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
        };
    };
    provider_list: {
        parameters: {
            query?: {
                /** @description Facility slug */
                facility?: string;
                /** @description rw | en | fr | sw */
                language?: string;
                limit?: number;
                /** @description Name or specialty */
                search?: string;
                /** @description ServiceType code */
                service?: string;
                /** @description Specialty code */
                specialty?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    provider_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetail"];
                };
            };
        };
    };
    queue_board_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    queue_current_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
        };
    };
    queue_entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckIn"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckIn"];
                "multipart/form-data": components["schemas"]["CheckIn"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    queue_entries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
        };
    };
    queue_entry_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntry"];
                };
            };
        };
    };
    queue_sync_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Sync"];
                "application/x-www-form-urlencoded": components["schemas"]["Sync"];
                "multipart/form-data": components["schemas"]["Sync"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    global_search: {
        parameters: {
            query: {
                /** @description Orders facilities by distance */
                lat?: number;
                lng?: number;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    service_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypeList"];
                };
            };
        };
    };
    specialties_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialtyList"];
                };
            };
        };
    };
    staff_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe"];
                };
            };
        };
    };
    triage_sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageSession"];
                };
            };
        };
    };
    triage_sessions_answer_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
                "application/x-www-form-urlencoded": components["schemas"]["Answer"];
                "multipart/form-data": components["schemas"]["Answer"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageSession"];
                };
            };
        };
    };
    triage_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageStatus"];
                };
            };
        };
    };
}
