/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Districts with verified facilities
         * @description Drives the fallback picker when geolocation is denied or out of bounds,
         *     and the first USSD menu in Phase 3.
         */
        get: operations["districts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facility detail */
        get: operations["facilities_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facilities/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearby facilities
         * @description Verified facilities near a coordinate, ranked by (tier, distance). Results are never ranked by wait time - only a minority of facilities report queue data, so ranking on it would bury good facilities that simply do not report.
         */
        get: operations["facilities_nearby_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insurers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insurers
         * @description Reference list. Changes perhaps twice a year - cache for 24h client-side.
         */
        get: operations["insurers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue board for the caller's facility
         * @description Everything the reception screen needs, grouped by service.
         */
        get: operations["queue_board_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check a patient in
         * @description The most performance-sensitive write in the system. Send an Idempotency-Key header: a retry after a network timeout must return the original entry, not create a duplicate.
         */
        post: operations["queue_entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One queue entry (patient-facing view)
         * @description Polled by the patient every 20 seconds in Phase 2.
         *
         *     Public by ticket id for now; Phase 2 binds it to the patient's JWT so that
         *     an enumerated id cannot reveal someone else's position.
         */
        get: operations["queue_entries_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/entries/{id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a queue entry: call, serve, skip or cancel */
        post: operations["queue_entry_transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay actions recorded while the reception client was offline
         * @description Apply queued offline actions, oldest client timestamp first.
         *
         *     Per-item results, so one rejected action does not fail the whole batch -
         *     a receptionist reconnecting after an hour must not lose the other 39
         *     check-ins because one patient was a duplicate.
         */
        post: operations["queue_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service types
         * @description Small, cacheable reference list. Includes all three language names so
         *     that USSD and WhatsApp can render without a second call.
         */
        get: operations["service_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in staff member and their facility
         * @description The reception client calls this on load to learn which facility it is
         *     operating, and which services that facility offers.
         */
        get: operations["staff_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Board: {
            facility: components["schemas"]["BoardFacility"];
            as_of: string;
            services: components["schemas"]["ServiceGroup"][];
        };
        BoardFacility: {
            name: string;
            slug: string;
        };
        /**
         * @description Minimal on purpose.
         *
         *     Target is under 10 seconds of human time per check-in, so the payload is a
         *     service plus one identifier. `facility` is never accepted from the client -
         *     it is derived from the authenticated staff member, so a receptionist cannot
         *     check a patient into another facility.
         */
        CheckIn: {
            service: string;
            phone?: string;
            walk_in_name?: string;
            /** Format: date-time */
            client_recorded_at?: string;
        };
        /** @description The check-in response is an entry plus its live ETA fields. */
        CheckInResponse: {
            readonly id: number;
            readonly ticket_code: string;
            /**
             * @description Masked too.
             *
             *     The model's display_name property falls back to the raw phone when a
             *     patient has no name on file. Masking `phone` while echoing the same
             *     number in `display_name` would defeat the point, so the fallback is
             *     masked here as well.
             */
            readonly display_name: string;
            /**
             * @description Masked. A queue board is readable across a reception desk, and a
             *     full phone number on screen is a needless disclosure.
             */
            readonly phone: string;
            readonly service: string;
            readonly status: components["schemas"]["QueueEntryStatusEnum"];
            readonly position: number;
            /** Format: date-time */
            readonly joined_at: string;
            /** Format: date-time */
            readonly called_at: string | null;
            readonly waited_minutes: number;
            eta_minutes: number | null;
            eta_confidence: string | null;
            people_ahead: number;
        };
        DistrictList: {
            results: string[];
        };
        FacilityDetail: {
            readonly id: number;
            slug: string;
            name: string;
            level: components["schemas"]["LevelEnum"];
            ownership: components["schemas"]["OwnershipEnum"];
            province?: string;
            district: string;
            sector?: string;
            address?: string;
            readonly location: components["schemas"]["LocationField"];
            phone?: string;
            /** Format: email */
            email?: string;
            readonly is_open: boolean;
            readonly opening_hours: components["schemas"]["OpeningHours"][];
            readonly insurers: components["schemas"]["InsurerBrief"][];
            readonly services: components["schemas"]["ServiceBrief"][];
            readonly wait: components["schemas"]["Wait"];
            readonly directions_url: string;
            /** Format: date-time */
            verified_at?: string | null;
        };
        FacilityNearby: {
            readonly id: number;
            slug: string;
            name: string;
            level: components["schemas"]["LevelEnum"];
            ownership: components["schemas"]["OwnershipEnum"];
            district: string;
            sector?: string;
            readonly location: components["schemas"]["LocationField"];
            readonly distance_m: number;
            phone?: string;
            readonly is_open: boolean;
            readonly opens_at: string | null;
            readonly closes_at: string | null;
            /** @description A patient must not travel to a door that shuts on arrival. */
            readonly closing_soon: boolean;
            readonly accepts_insurer: boolean;
            readonly insurers: string[];
            readonly services: string[];
            readonly wait: components["schemas"]["Wait"];
            readonly bookable: boolean;
        };
        Insurer: {
            code: string;
            name: string;
            is_public: boolean;
        };
        InsurerBrief: {
            code: string;
            name: string;
            note: string;
        };
        InsurerList: {
            results: components["schemas"]["Insurer"][];
        };
        /**
         * @description * `health_post` - Health post
         *     * `health_centre` - Health centre
         *     * `district_hospital` - District hospital
         *     * `referral_hospital` - Referral hospital
         *     * `clinic` - Clinic / polyclinic
         *     * `pharmacy` - Pharmacy
         * @enum {string}
         */
        LevelEnum: "health_post" | "health_centre" | "district_hospital" | "referral_hospital" | "clinic" | "pharmacy";
        LocationField: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        NearbyQueryEcho: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            radius: number;
            radius_expanded: boolean;
            insurer: string | null;
            service: string | null;
            open_now: boolean;
        };
        NearbyResponse: {
            as_of: string;
            query: components["schemas"]["NearbyQueryEcho"];
            count: number;
            results: components["schemas"]["FacilityNearby"][];
        };
        OpeningHours: {
            weekday: number;
            /** Format: time */
            opens_at: string;
            /** Format: time */
            closes_at: string;
        };
        /**
         * @description * `public` - Public
         *     * `private` - Private
         *     * `faith_based` - Faith-based
         * @enum {string}
         */
        OwnershipEnum: "public" | "private" | "faith_based";
        /** @description Staff-facing view of one entry. */
        QueueEntry: {
            readonly id: number;
            readonly ticket_code: string;
            /**
             * @description Masked too.
             *
             *     The model's display_name property falls back to the raw phone when a
             *     patient has no name on file. Masking `phone` while echoing the same
             *     number in `display_name` would defeat the point, so the fallback is
             *     masked here as well.
             */
            readonly display_name: string;
            /**
             * @description Masked. A queue board is readable across a reception desk, and a
             *     full phone number on screen is a needless disclosure.
             */
            readonly phone: string;
            readonly service: string;
            readonly status: components["schemas"]["QueueEntryStatusEnum"];
            readonly position: number;
            /** Format: date-time */
            readonly joined_at: string;
            /** Format: date-time */
            readonly called_at: string | null;
            readonly waited_minutes: number;
        };
        /**
         * @description Patient-facing view - no other patient's details, ever.
         *
         *     Phase 2 adds leave_by and travel_minutes here.
         */
        QueueEntryPublic: {
            readonly id: number;
            readonly facility: components["schemas"]["QueueFacility"];
            readonly service: string;
            readonly ticket_code: string;
            readonly status: components["schemas"]["QueueEntryStatusEnum"];
            readonly position: number;
            readonly people_ahead: number;
            readonly eta_minutes: number | null;
            readonly eta_confidence: string | null;
            /** Format: date-time */
            readonly joined_at: string;
            readonly as_of: string;
        };
        /**
         * @description * `waiting` - Waiting
         *     * `called` - Called
         *     * `served` - Served
         *     * `left` - Left without being seen
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        QueueEntryStatusEnum: "waiting" | "called" | "served" | "left" | "cancelled";
        QueueFacility: {
            name: string;
            slug: string;
            location: components["schemas"]["QueueLocation"];
        };
        QueueLocation: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        ServiceBrief: {
            code: string;
            name_rw: string;
            name_en: string;
            name_fr: string;
        };
        ServiceGroup: {
            service: string;
            service_name_rw: string;
            service_name_en: string;
            waiting: components["schemas"]["QueueEntry"][];
            called: components["schemas"]["QueueEntry"][];
        };
        ServiceType: {
            code: string;
            name_rw: string;
            name_en: string;
            name_fr: string;
        };
        ServiceTypeList: {
            results: components["schemas"]["ServiceType"][];
        };
        StaffFacility: {
            id: number;
            slug: string;
            name: string;
            district: string;
            reports_queue: boolean;
        };
        StaffMe: {
            username: string;
            role: string;
            can_manage_queue: boolean;
            facility: components["schemas"]["StaffFacility"];
            services: components["schemas"]["StaffService"][];
        };
        StaffService: {
            code: string;
            name_rw: string;
            name_en: string;
        };
        Sync: {
            actions: components["schemas"]["SyncAction"][];
        };
        SyncAction: {
            key: string;
            type: components["schemas"]["TypeEnum"];
            /** Format: date-time */
            client_recorded_at: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        SyncResponse: {
            applied: number;
            rejected: number;
            results: components["schemas"]["SyncResultRow"][];
        };
        SyncResultRow: {
            key: string;
            ok: boolean;
            created?: boolean;
            entry_id?: number;
            ticket_code?: string;
            error?: string;
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /**
         * @description * `check_in` - check_in
         *     * `call` - call
         *     * `serve` - serve
         *     * `skip` - skip
         *     * `cancel` - cancel
         * @enum {string}
         */
        TypeEnum: "check_in" | "call" | "serve" | "skip" | "cancel";
        /**
         * @description The wait contract, enforced in the OpenAPI schema itself.
         *
         *     `status` is a ChoiceField rather than a CharField so the generated
         *     TypeScript client gets a closed union and a client that forgets to
         *     handle one of the four states fails to compile. There is deliberately
         *     no value meaning "estimated" - we never guess a wait time.
         */
        Wait: {
            status: components["schemas"]["WaitStatusEnum"];
            minutes: number | null;
            people_waiting: number | null;
            as_of: string;
        };
        /**
         * @description * `available` - available
         *     * `not_reported` - not_reported
         *     * `insufficient_data` - insufficient_data
         *     * `closed` - closed
         * @enum {string}
         */
        WaitStatusEnum: "available" | "not_reported" | "insufficient_data" | "closed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    districts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictList"];
                };
            };
        };
    };
    facilities_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDetail"];
                };
            };
        };
    };
    facilities_nearby_retrieve: {
        parameters: {
            query: {
                /** @description Insurer code, e.g. mutuelle */
                insurer?: string;
                lat: number;
                level?: string[];
                limit?: number;
                lng: number;
                open_now?: boolean;
                /** @description Metres. Default 5000, max 50000. */
                radius?: number;
                /** @description Service type code */
                service?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyResponse"];
                };
            };
        };
    };
    insurers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsurerList"];
                };
            };
        };
    };
    queue_board_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    queue_entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckIn"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckIn"];
                "multipart/form-data": components["schemas"]["CheckIn"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    queue_entries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
        };
    };
    queue_entry_transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntry"];
                };
            };
        };
    };
    queue_sync_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Sync"];
                "application/x-www-form-urlencoded": components["schemas"]["Sync"];
                "multipart/form-data": components["schemas"]["Sync"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    service_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypeList"];
                };
            };
        };
    };
    staff_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe"];
                };
            };
        };
    };
}
