# Generated by Django 5.0.14 on 2026-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriageOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_version', models.CharField(max_length=20)),
                ('recommended_service', models.CharField(blank=True, max_length=40)),
                ('escalated_emergency', models.BooleanField(default=False)),
                ('questions_answered', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('hour_bucket', models.SmallIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['protocol_version', 'date'], name='triage_version_date_idx')],
            },
        ),
    ]
