# Generated by Django 5.0.14 on 2026-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Web push')], max_length=6)),
                ('kind', models.CharField(choices=[('otp', 'Sign-in code'), ('leave_now', 'Leave now'), ('called', 'You have been called'), ('appt_reminder_24h', 'Appointment reminder (24h)'), ('appt_reminder_2h', 'Appointment reminder (2h)'), ('appt_cancelled', 'Appointment cancelled')], max_length=24)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('provider_ref', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
