# Generated by Django 5.0.14 on 2026-08-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('patients', '0002_otpcode'),
        ('queueing', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='notification',
            name='queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queueing.queueentry'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['phone', 'created_at'], name='notification_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('queue_entry__isnull', False)), fields=('queue_entry', 'kind'), name='one_notification_per_kind_per_queue_entry'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('appointment', 'kind'), name='one_notification_per_kind_per_appointment'),
        ),
    ]
