# Generated by Django 5.0.14 on 2026-08-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('patients', '0004_patientaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('otp', 'Sign-in code'), ('leave_now', 'Leave now'), ('called', 'You have been called'), ('appt_reminder_24h', 'Appointment reminder (24h)'), ('appt_reminder_2h', 'Appointment reminder (2h)'), ('appt_cancelled', 'Appointment cancelled')], max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='patients.patient')),
            ],
            options={
                'ordering': ['kind'],
                'unique_together': {('patient', 'kind')},
            },
        ),
    ]
