services:
  db:
    image: postgis/postgis:16-3.4
    container_name: medilink-db
    environment:
      POSTGRES_DB: medilink
      POSTGRES_USER: medilink
      POSTGRES_PASSWORD: medilink
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medilink -d medilink"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: medilink-redis
    ports: ["6380:6379"]   # 6379 often taken by another local project
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

volumes:
  pgdata:
