# Generated by Django 5.0.14 on 2026-08-20 16:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name_rw', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True)),
                ('is_triage_target', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('service_types', models.ManyToManyField(blank=True, help_text='Facility services a clinician in this specialty delivers.', related_name='specialties', to='facilities.servicetype')),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(blank=True, choices=[('dr', 'Dr'), ('prof', 'Prof'), ('sister', 'Sister'), ('mr', 'Mr'), ('ms', 'Ms'), ('', '(none)')], default='dr', max_length=8)),
                ('full_name', models.CharField(max_length=150)),
                ('photo_url', models.URLField(blank=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rw', 'Kinyarwanda'), ('en', 'English'), ('fr', 'Francais'), ('sw', 'Kiswahili')], max_length=2), blank=True, default=list, help_text='Languages this clinician can consult in.', size=None)),
                ('bio_en', models.TextField(blank=True, help_text='Short professional summary. Never enter qualifications or claims that have not been verified - see docs/11 section 7.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='providers', to='providers.specialty')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, help_text='e.g. Consultant, Head of Paediatrics', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='facilities.facility')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='providers.provider')),
                ('service_types', models.ManyToManyField(blank=True, related_name='providers', to='facilities.servicetype')),
                ('staff_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_placement', to='staff.staffmember')),
            ],
            options={
                'verbose_name_plural': 'provider placements',
                'ordering': ['provider__full_name'],
                'indexes': [models.Index(fields=['facility', 'active'], name='placement_facility_idx')],
                'unique_together': {('provider', 'facility')},
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['active'], name='provider_active_idx'),
        ),
    ]
