# Generated by Django 5.0.14 on 2026-08-18 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_of_day', models.SmallIntegerField()),
                ('median_minutes', models.FloatField()),
                ('sample_size', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_in_name', models.CharField(blank=True, max_length=150)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('served', 'Served'), ('left', 'Left without being seen'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('ticket_code', models.CharField(blank=True, max_length=8)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='facilities.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='patients.patient')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.servicetype')),
            ],
            options={
                'verbose_name_plural': 'queue entries',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['facility', 'service_type', 'status', 'joined_at'], name='queue_position_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('facility', 'idempotency_key'), name='unique_idempotency_key_per_facility'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetimestat',
            unique_together={('facility', 'service_type', 'hour_of_day')},
        ),
    ]
