# Generated by Django 5.2.17 on 2026-08-24 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('patients', '0006_patient_consent_version_patient_consented_at'),
        ('queueing', '0002_service_rate_not_wait'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='ticket_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_day__isnull', False)), fields=('facility', 'service_type', 'ticket_day', 'ticket_code'), name='unique_ticket_code_per_day'),
        ),
    ]
