# Generated by Django 5.0.14 on 2026-08-18 21:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('language', models.CharField(choices=[('rw', 'Kinyarwanda'), ('en', 'English'), ('fr', 'Francais')], default='rw', max_length=2)),
                ('national_id_hash', models.CharField(blank=True, max_length=64)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insurer')),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='patient_phone_idx')],
            },
        ),
    ]
