# Generated by Django 5.0.14 on 2026-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
