# Generated by Django 5.0.14 on 2026-08-20 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('patients', '0003_patient_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('board', 'Viewed queue board'), ('view', 'Viewed a patient record'), ('check_in', 'Checked a patient in'), ('transition', 'Changed a queue entry'), ('update', 'Updated a patient record'), ('export', 'Exported own data'), ('erase', 'Erased own data')], max_length=12)),
                ('record_count', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('acting_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_access_logs', to='patients.patient')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='patients.patient')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['actor', 'occurred_at'], name='access_actor_idx'), models.Index(fields=['patient', 'occurred_at'], name='access_patient_idx')],
            },
        ),
    ]
