# Generated by Django 5.0.14 on 2026-08-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_password_patient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
