# Generated by Django 5.0.14 on 2026-08-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityServiceInsurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(choices=[('full', 'Fully covered'), ('partial', 'Partially covered'), ('not_covered', 'Not covered'), ('unknown', 'Not confirmed')], default='unknown', max_length=12)),
                ('note', models.CharField(blank=True, help_text="Any condition the facility stated, e.g. 'referral required'.", max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('facility_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_coverage', to='facilities.facilityservice')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insurer')),
            ],
            options={
                'ordering': ['insurer__sort_order'],
                'unique_together': {('facility_service', 'insurer')},
            },
        ),
    ]
