# Generated by Django 5.0.14 on 2026-08-19 12:56

import apps.scheduling.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('patients', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('capacity_per_slot', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='facilities.facility')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.servicetype')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived'), ('served', 'Served'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='booked', max_length=12)),
                ('booked_via', models.CharField(choices=[('app', 'App'), ('ussd', 'USSD'), ('whatsapp', 'WhatsApp'), ('desk', 'Reception desk')], default='app', max_length=12)),
                ('reference', models.CharField(default=apps.scheduling.models.new_reference, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.servicetype')),
            ],
            options={
                'ordering': ['slot_start'],
                'indexes': [models.Index(fields=['facility', 'slot_start'], name='appointment_facility_idx'), models.Index(fields=['patient', 'slot_start'], name='appointment_patient_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'arrived'])), fields=('patient', 'facility', 'slot_start'), name='one_active_appointment_per_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together={('facility', 'service_type', 'weekday', 'start_time')},
        ),
    ]
