# Generated by Django 5.0.14 on 2026-08-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('providers', '0001_initial'),
        ('scheduling', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='providers.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together={('facility', 'service_type', 'provider', 'weekday', 'start_time')},
        ),
    ]
