# Generated by Django 5.2.17 on 2026-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_scheduletemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived'), ('served', 'Served'), ('no_show', 'No show'), ('cancelled', 'Cancelled'), ('unrecorded', 'Arrived, outcome not recorded')], default='booked', max_length=12),
        ),
    ]
