# Generated by Django 5.2.17 on 2026-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_location_gist'),
        ('providers', '0001_initial'),
        ('scheduling', '0004_appointment_unrecorded_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scheduletemplate',
            constraint=models.UniqueConstraint(fields=('facility', 'service_type', 'provider', 'weekday', 'start_time'), name='unique_session_per_slot_start', nulls_distinct=False),
        ),
    ]
